### PR TITLE
Only from PHP 8.0

### PR DESCRIPTION
**Pull request by Justman10000**
I had Debian 11 and PHP 7.4 on it, only after uninstalling PHP 7.4 and installing PHP 8.0 did it work!

### CODE REVIEW

**Comment by Software-Noob** [comment]
7.4 and 8.0 are both supported. Distro version doesn't affect the PHP requirements

**Comment by Justman10000** [comment]
> 

Well, for me it only works with PHP 8.0...

**Comment by hwalker928** [comment]
Are you sure it wasn't just an NGINX configuration issue?

**Comment by Software-Noob** [comment]
That would not be up to the distro and rather your configuration. Most likely your web server virtual host was set to php 8.

Both php 7.4 and 8.0 are supported as listed in the [required dependencies](https://pterodactyl.io/panel/1.0/getting_started.html#dependencies)

**Pull request closed without merging**
