### PR TITLE
Update PHP installation instructions

### PR DESCRIPTION
**Pull request by Nuc1eoN**
Ubuntu and Debian might also need to be updated

### CODE REVIEW

**Comment by Nuc1eoN** [comment]
Changes as suggested in #92

**Comment by DaneEveritt** [comment]
7.2 remains the officially supported version, I will manually change this when I am ready to change the officially supported version and requirements.

**Comment by Nuc1eoN** [comment]
The issue is that the current instructions are borked so any new user will not know what to do see #92

**Comment by DaneEveritt** [comment]
Then the broken packages should be removed or addressed, I'm not comfortable just bumping the recommended version like that.

**Comment by Nuc1eoN** [comment]
I just think it's better to have a working than a broken documentation but that is your decision.

**Pull request closed without merging**
