### PR TITLE
Corrected the footer year

### PR DESCRIPTION
**Pull request by DomiiBunn**

### CODE REVIEW

**Comment by schrej** [comment]
I think that doesn't really change the footer year on the frontpage. Not sure if it helps at all. I've opened another PR for the frontpage: #120

**Comment by DomiiBunn** [comment]
I belie both of them are responsible for the footer :/ Tho i think the README takes priority with vuepress. Not sure tho

**Comment by schrej** [comment]
That would be true if we'd actually use the page frontmatter on the Home.vue page. Maybe we should change that. Feel free to do so in this PR but please test if it works properly.

**Comment by DomiiBunn** [comment]
Ima joink the reppo to my dev server give me a few

**Comment by DomiiBunn** [comment]
you know where are these from?
```vue
    postcss: {
        plugins: [
            require('postcss-import'),
            require('tailwindcss')('./tailwind.js'),
            require('precss'),
            require('autoprefixer'),
            require('cssnano'),
        ]
    }```
I can't get vuepress to run cuz it can't find the modules :/

**Comment by schrej** [comment]
Should be npm, run `npm install` or `yarn` if you have it

**Pull request closed without merging**
