### PR TITLE
Add "Yolk" and "Docker image" term to terminology

### PR DESCRIPTION
**Pull request by Boy132**
Because some people in discord sometimes ask what a "yolk" is.

### CODE REVIEW

**Comment by Software-Noob** [comment]
This doesn't feel like an explanation of what Yolks project actually is.

> A curated collection of core docker images that can be used with Pterodactyl's Egg system. Each image is rebuilt periodically to ensure dependencies are always up-to-date.

To explain what Yolks is, we'd also have to provide a foundation for what image is (quick example)
> Docker Image - Contains everything needed to run a containerized application, such as libraries, tools, and dependencies.

**Comment by Boy132** [comment]
> 
> 
> This doesn't feel like an explanation of what Yolks project actually is.
> 
> > A curated collection of core docker images that can be used with Pterodactyl's Egg system. Each image is rebuilt periodically to ensure dependencies are always up-to-date.
> 
> To explain what Yolks is, we'd also have to provide a foundation for what image is (quick example)
> 
> > Docker Image - Contains everything needed to run a containerized application, such as libraries, tools, and dependencies.

I've changed the wording. I hope the explanation is clearer now.

**Comment by Software-Noob** [comment]
The docker image should be separated into a different term similar to my previous example

**Comment by Boy132** [comment]
> 
> 
> The docker image should be separated into a different term similar to my previous example and be put above Yolks term explanation

Done. :)

**Review by Software-Noob — APPROVED** [review]
LGTM, thank you for the contribution!

**Pull request merged**
