### PR TITLE
WISP Infomercial

### PR DESCRIPTION
**Pull request by WISPdotGG**
Contextually relevent info for people who want easier setup

### CODE REVIEW

**Comment by DaneEveritt** [comment]
Yes this has my blessing before anyone comments on that. 👍

**Comment by DaneEveritt** [comment]
@WISPdotGG Did you want to do like a banner graphic or something for this rather than just text? Or do like a left logo and text on the right? People generally ignore the info banners that are just text.

**Comment by WISPdotGG** [comment]
> a left logo and text on the right? People generally ignore the info banners that are just text.

I think a banner would be too intrusive, but a logo to make it stand out more would be nice. I'm not familiar with how you would do that on the system you're using. I can get our logo in a specific size if you're able to add the logo in for me?

**Comment by DaneEveritt** [comment]
Yeah if you provide the logo here I can fiddle around and see if I can get it added in correctly.

**Comment by WISPdotGG** [comment]
[logo.zip](https://github.com/pterodactyl/documentation/files/5626278/logo.zip)

**Comment by DaneEveritt** [comment]
I actually have no clue how to do this right now, so I'm gonna merge this until I can figure it out lol.

**Pull request merged**
