### PR TITLE
Add caddy instructions

### PR DESCRIPTION
**Pull request by HandyHat**
A similar config can be seen here: https://caddy.community/t/nginx-config-translation-help/8166

### CODE REVIEW

**Comment by Software-Noob** [comment]
There should be an option to have both SSL and non-SSL options for users that don't have a domain, since Letsencrypt certificates are only valid for domains. The latter can be achieved by adding `tls off` or specifying `http:// <domain>` for the host.

I have not tried running Laravel app in Caddy itself, so personally, I would have to test first to comment on anything else.

**Comment by HandyHat** [comment]
> 
> 
> There should be an option to have both SSL and non-SSL options for users that don't have a domain, since Letsencrypt certificates are only valid for domains unless ZeroSSL is configured. The latter can be achieved by adding `tls off` or specifying `http:// <domain>` for the host.
> 
> I have not tried running Laravel app in Caddy itself, so personally, I would have to test first to comment on anything else.

I've added instructions for using Caddy without SSL.

**Comment by WavingCatDevs** [comment]
Is this going to be ever merged lol

**Comment by parkervcp** [comment]
I am going to close this in favor of #535

**Pull request closed without merging**
