### PR TITLE
Update Community Guides to 1.0

### PR DESCRIPTION
**Pull request by gamer4life1**
Update community guide to 1.0 and fix some links. I have only done ubuntu 18.04 so far, but I will do the next ones.

### CODE REVIEW

**Comment by parkervcp** [comment]
heh i missed some stuff...

**Comment by gamer4life1** [comment]
It's just some wording and links...

**Comment by gamer4life1** [comment]
I'm also going to fix #256 really quickly...

**Comment by gamer4life1** [comment]
Let me know if you need anything changed...

**Comment by notOM3GA** [comment]
This really only updates wings, it doesn't update all other sides of the community guides.

**Comment by gamer4life1** [comment]
I will look at the panel guides...

**Comment by gamer4life1** [comment]
@notOM3GA I have updated the panel as well!

**Comment by notOM3GA** [comment]
Thanks!

**Comment by gamer4life1** [comment]
Let me know if there's anything else that I should add

**Comment by gamer4life1** [comment]
@parkervcp I have found [another thing to update](https://github.com/pterodactyl/documentation/blob/master/community/config/nodes/add_node.md). However, the screenshot is out of date.

**Comment by parkervcp** [comment]
Those are still mostly correct all things considered.

**Comment by gamer4life1** [comment]
All right, let me know if there's anything else. Thanks!

**Review by parkervcp — APPROVED** [review]

**Pull request merged**
