### PR TITLE
Update debian10.md

### PR DESCRIPTION
**Pull request by IdrisMC**
Replaced the Deb 9 packages with Deb 10 otherwise it will cause issues with dependencies.

### CODE REVIEW

**Comment by devil38** [comment]
Debian 10 have PHP 7.3 NodeJS 10 and MariaDB 10.3 included
No repository needed

**Comment by IdrisMC** [comment]
`~# apt install -y php7.3 php7.3-cli php7.3-gd php7.3-mysql php7.3-pdo php7.3-mbstring php7.3-tokenizer php7.3-bcmath php7.3-xml php7.3-fpm php7.3-curl php7.3-zip
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'php7.3-common' instead of 'php7.3-pdo'
Note, selecting 'php7.3-common' instead of 'php7.3-tokenizer'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php7.3-curl : Depends: libcurl3 (>= 7.44.0) but it is not installable
E: Unable to correct problems, you have held broken `packages``
You get this if you don't run the command

**Comment by devil38** [comment]
You broke php packages by adding PHP repo

**Comment by IdrisMC** [comment]
Well I ran all the commands from the doc and nothing else, but got a error when running
apt install -y php7.3 php7.3-cli php7.3-gd php7.3-mysql php7.3-pdo php7.3-mbstring php7.3-tokenizer php7.3-bcmath php7.3-xml php7.3-fpm php7.3-curl php7.3-zip
the buster packages seemed to fixed it.

**Comment by parkervcp** [comment]
Calling #157 integrates this and other changes suggested by just removing the repo all together. Closing this out for that one.

**Pull request closed without merging**
