### PR TITLE
Important! Fix mysql issue

### PR DESCRIPTION
**Pull request by DomiiBunn**
Fixed where it was suggesting to add a user to 127.0.0.1 user group and grant perms on a % user group user. This will cause a user not found error

### CODE REVIEW

**Comment by schrej** [comment]
There is a fat red warning below the SQL statement indicating to replace `127.0.0.1` with `%` if the database host is different than the panel host. If it's the same host, the current way is more secure.

**Comment by schrej** [comment]
If you want to fix it, do it [here](https://github.com/pterodactyl/documentation/blame/master/tutorials/mysql_setup.md#L73).

**Comment by DomiiBunn** [comment]
I am aware whoever. If you go through it one by one you'll find that you get an error of the user not existing.... I wouldn't add a comit like this to my own pr if I didn't find the issue....... Also since pteordactyl network isn't 127.0.0.1 this is an issue

**Comment by DomiiBunn** [comment]
Or maybe i'm just dumb. both can be the case

**Comment by schrej** [comment]
The created user is for the panel so it can connect to the DB in order to create and delete databases.

**Pull request closed without merging**
