### PR TITLE
add sql warning for node db

### PR DESCRIPTION
**Pull request by parkervcp**
This is to add a warning about this not being how to configure a server to connect to a DB.

People probably won't read this either way.

### CODE REVIEW

**Comment by DaneEveritt** [comment]
What does this even mean? I wrote most of this page and this callout is not clicking at all.

**Comment by parkervcp** [comment]
It's specifically calling out the setting up a db for a node section.

apparently people are saying it makes them think they can set their game servers to 127.0.0.1

**Comment by DaneEveritt** [comment]
This now makes even less sense.

**Comment by DaneEveritt** [comment]
Honestly I don't even see how this would do anything, people ignore all of the giant red boxes anyways. If they don't know they shouldn't use 127.0.0.1 this isn't going to change anything.

**Comment by parkervcp** [comment]
I get that it's not being read in the first place by many, but I am sure this will at least catch some people.

**Pull request closed without merging**
