### PR TITLE
docs(wings): Show tip to figure out architecture

### PR DESCRIPTION
**Pull request by Boy132**
Follow up to #418.
Seems like the other PR confuses some people on what they need to use. This tip should help.

### CODE REVIEW

**Comment by DaneEveritt** [comment]
@Software-Noob is there a reason we can't use tabs here?

**Comment by Boy132** [comment]
> @Software-Noob is there a reason we can't use tabs here?

Aren't tabs for these subtle differences between the two instructions a bit "overkill"? Sure they would look nicer but the content would be 99% the same, wouldn't it?

**Comment by Software-Noob** [comment]
> @Software-Noob is there a reason we can't use tabs here?

We could and should, but last PR of tabs caused hydration issue occasionally that made the whole tab modal disappear and thus break whole documentation.

I could not figure out why nor replicate it in my own setups. Can't really test on master docs since it's a protected branch and reviews of new PRs takes time

**Comment by DaneEveritt** [comment]
I think this current format is unnecessarily confusing, only a small percentage of users need the ARM build. Perhaps just drop the whole section for downloading it, and just make a tip box that lets a user know there is an arm specific build and to replace `wings_linux_amd64` with `wings_linux_arm64`.

**Comment by Software-Noob** [comment]
I agree that they're a bit confusing right now.  We could use something like this instead?

```bash
mkdir -p /etc/pterodactyl
curl -L -o /usr/local/bin/wings https://github.com/pterodactyl/wings/releases/latest/download/wings_linux_$([[ "$(uname -m)" == "aarch64" ]] && echo "arm64" || echo "amd64")
chmod u+x /usr/local/bin/wings
```

**Pull request closed without merging**
