### PR TITLE
Added node-gyp

### PR DESCRIPTION
**Pull request by Sir3lit**
Added node-gyp to dependencies

### CODE REVIEW

**Comment by lancepioch** [comment]
@Sir3lit Can you post your full output showing your input and the respective output that requires this change? Thanks!

**Comment by Sir3lit** [comment]
I don't understand why you need that, get a fresh install of Ubuntu literally follow the guide as you would and when you get to npm install if fails because node-gyp isn't installed

**Comment by lancepioch** [comment]
@Sir3lit I don't get that. Here's my output (this is a fresh Ubuntu instance):

image

**Comment by parkervcp** [comment]
I have had no issues with installing the daemon on Ubuntu either. We just want to see what exactly is failing for you.

**Comment by DaneEveritt** [comment]
I'm fine adding this, but it is typo'd

**Comment by Sir3lit** [comment]
Fixed

**Pull request merged**
