### PR TITLE
Removed FiveM

### PR DESCRIPTION
**Pull request by AndreasTheDead**
After the latest Problems with FiveM I noticed that it should be removed from the Supportet Game List.

### CODE REVIEW

**Comment by parkervcp** [comment]
Technically it still works just not out of the box.

**Comment by AndreasTheDead** [comment]
Yes, i know, i thought. iit should be the Point "and More" because you cannot guarantee that it will work in the future.

**Comment by Software-Noob** [comment]
FiveM itself is a community-made egg located in the Parkers repository to which the documentation provides a link. It's not a core official egg of the Panel itself. Personally, I don't see the need for this change. 

> Yes, i know, i thought. iit should be the Point "and More" because you cannot guarantee that it will work in the future.

We can't guarantee that any egg will work in the future. They all require changes and updates at some point.

**Comment by BenasPaulikas** [comment]
#boicot_fivem

**Pull request closed without merging**
