### PR TITLE
Update to php7.4

### PR DESCRIPTION
**Pull request by TekExplorer**
Update the community guides to php 7.4, but better

### CODE REVIEW

**Review by DomiiBunn — APPROVED** [review]

**Comment by TekExplorer** [comment]
any updates regarding this?

**Comment by DomiiBunn** [comment]
I dif say that with my english skills I'm not the best person to do it :)

**Comment by TekExplorer** [comment]
I think you may have mixed up repos Domii

**Comment by DomiiBunn** [comment]
I most certainly did. I don't even know why I got an email for this issue

**Review by parkervcp — APPROVED** [review]

**Pull request merged**
