### PR TITLE
Add TIP to swap limit block

### PR DESCRIPTION
**Pull request by realkarmakun**
Resolves https://github.com/pterodactyl/documentation/issues/397

### CODE REVIEW

**Comment by realkarmakun** [comment]
I'm not native English speaker, so text probably needs to be modified.

**Comment by Software-Noob** [comment]
`GRUB_CMDLINE_LINUX_DEFAULT` appends entries to the linux line in normal boot mode, while `GRUB_CMDLINE_LINUX` applies to both normal and recovery bot mode.

 I don't see how it would be ignored during normal boot unless this is another one of the OVH quirks or you are in recovery, do you have any source for this?

**Comment by realkarmakun** [comment]
> I don't see how it would be ignored during normal boot unless this is another one of the OVH quirks or you are in recovery, do you have any source for this?

I am kinda my own source, I ran into the issue on OVH bare-metal servers. Though I have been buying servers more and more servers for a year or so and lately there was no quirks around `/home` directory. Even though it used to be that way. But I was updating some of my servers to newer distro version so maybe it's just distribution update issue. I'll try asking in OVH support about this.

**Comment by realkarmakun** [comment]
Sorry for taking so long. Here is supports answer.
Transcript:
me:
```
Additional information:
My /etc/default/grub lacks GRUB_CMDLINE_LINUX_DEFAULT line. 
Is it ignored by OS when using OVH servers? Is it default behavior?
 I'm writing down some documentation, so I'd like to know if this is normal for all OVH bare metal servers.
```
OVH:
```
Refering your request about GRUB configuration files, we confirm that your server seems to be currently installed with Ubuntu20.04 version distribution.

This distribution template has been taken directly from Ubuntu, there has been no modification on the configuration files.
So this means that if your server has a behaviour or specific configuration, it will be the same on all the servers that use this specific distribution.

If you reinstall the server with another distribution, the behaviour or configuration may be different.
```
And some proof:
изображение

Lack of GRUB_CMDLINE_LINUX_DEFAULT is default for Ubuntu 20.04. Can't really check since I'm on windows.

**Review by Software-Noob — APPROVED** [review]
Thanks, this tip might save unnecessary trouble for someone. I changed the wording a bit.

In the future, please do not use the `master` branch and instead create a new one. It makes it very annoying to work with.

**Pull request merged**
