### PR TITLE
Add links to community guides for supported os table, uniformity changes within community guides.

### PR DESCRIPTION
**Pull request by Sir3lit**
Added links to OS versions to show the community guide that's specific to that OS and version.
Community guides now state they're for v0.7, I'm sure they would work for v1.0 but they should be tested to make sure.

### CODE REVIEW

**Comment by schrej** [comment]
Could you _please_ give your PRs descriptive names in the future?
It's really annoying to have PRs with such a generic name. It's not that bad in the docs repo, but I've also seen it in the other repos as well.

**Comment by Sir3lit** [comment]
I mean prs have a description box? Do you not look over the files that people are changing?

**Comment by Sir3lit** [comment]
😊

**Comment by schrej** [comment]
I do, but right now I have about 200 GH notifications, and when I clean up once in a while it helps to see what an issue/pr is about.
It doesn't have to be too specific, but even something like "Improve community guides" is better than just "doc changes", because I already know you probably modified the docs when you PR to the documentation repository 😄

**Pull request merged**
