### PR TITLE
Add instructions for disabling recaptcha

### PR DESCRIPTION
**Pull request by iamkubi**

### CODE REVIEW

**Comment by matthewpi** [comment]
https://pterodactyl.io/panel/0.7/configuration.html#disable-or-modify-recaptcha

**Comment by iamkubi** [comment]
Yeah, I thought it was there somewhere but failed to find it.  It turns out the docs only show up if you search for "pterodactyl disable recaptcha" but not "pterodactyl disable captcha".

**Comment by matthewpi** [comment]
Even if you wanted to add it to that page you should link to the other one instead of writing it in two different places.

**Comment by schrej** [comment]
I think we should move it to troubleshooting.

**Comment by iamkubi** [comment]
I wrote the config:cache part based on a Github issue from 2017.  It's not in the current configuration guide, so I suspect it's not required.

**Pull request closed without merging**
