### PR TITLE
Remove grant option for panel db

### PR DESCRIPTION
**Pull request by DomiiBunn**
As title

### CODE REVIEW

**Comment by DaneEveritt** [comment]
If you read the sorrounding documentation you'll see that this is important in context. In addition, your PR includes no relevant information as to why you're making this change, or what the benefits/fixes as a result of it are.

**Comment by DomiiBunn** [comment]
Isn't the `GRANT OPTION` useless for just the panel as the next part of the guide https://pterodactyl.io/tutorials/mysql_setup.html#creating-a-database-host-for-nodes takes care of the nodes/server databases and i don't believe that the panel needs grant option for any other reason. Furthermore my panel instance (3 of em) all run on a db user without the `GRANT OPTION` perm. Dono tho. I would love to know what it is used for so? Since it just looks like a bit of a security risk atm....

**Comment by schrej** [comment]
Maybe actually _read_ the text above the code block you're changing.

**Comment by DomiiBunn** [comment]
Oh. I am just blind in multiple ways :^)

**Pull request closed without merging**
