### PR TITLE
Not access to Panel

### PR DESCRIPTION
**Pull request by Justman10000**
Without this, access to the panel will be denied!

### CODE REVIEW

**Comment by parkervcp** [comment]
So the several thousand other installs of the panel. How exactly does this fix what's not broken?

**Comment by Justman10000** [comment]
Like mine?

**Comment by DaneEveritt** [comment]
Please include relevant information as to why the PR should be merged, specifically what it is fixing and why it is necessary. I don't use Apache regularly so a PR like this is just going to be ignored unless you can explain more.

**Comment by Justman10000** [comment]
So ... Apache2 basically locks every directory on the entire operating system, unless you release this lock for directories (or files) with the code given above! In other words, without this code, access to the panel will be denied!

**Comment by DaneEveritt** [comment]
So what specifically about your setup is different though as @parkervcp was asking, since we've had this code for years without people running into issues.

**Comment by Justman10000** [comment]
> 
> 
> So what specifically about your setup is different though as @parkervcp was asking, since we've had this code for years without people running into issues.

So? Strange...

**Comment by fabm3n** [comment]
I can understand @Justman10000 because if you follow the security tips from the Apache docs (https://httpd.apache.org/docs/2.4/misc/security_tips.html#protectserverfiles) you should disallow the access to the whole filesystem and then reallow it again.
So maybe this should be merged (but with the other apache conf also be modified).

**Comment by parkervcp** [comment]
Most people are not following the apache security guidelines. The same goes for any other software out there.

**Comment by fabm3n** [comment]
> Most people are not following the apache security guidelines. The same goes for any other software out there.

Okay yeah that's true and if you are following this guide you should also be able to fix this issue on your own.

**Pull request merged**
