### PR TITLE
docs: do not specify PHP 7 version in meta tag

### PR DESCRIPTION
**Pull request by yesBad**
🤔

### CODE REVIEW

**Comment by devnote-dev** [comment]
Why not remove the version altogether?

**Comment by Software-Noob** [comment]
It's easier to not specify the version as done in other places of the documentation and Github

**Comment by yesBad** [comment]
better

**Review by Software-Noob — APPROVED** [review]
FYI this is only a meta tag. LGTM, thank you for the contribution :+1:

**Pull request merged**
