### PR TITLE
fpm extension is also needed

### PR DESCRIPTION
**Pull request by Nuc1eoN**

### CODE REVIEW

**Comment by DaneEveritt** [comment]
This is incorrect if the user is running Apache under default conditions.

**Comment by parkervcp** [comment]
Seeing as we favor nginx in our docs it may be worth it to call it out. Even if the install commands we offer install fpm already.

**Comment by DaneEveritt** [comment]
Then it should probably have a little note in parenthesis mentioning it is only needed for nginx.

**Comment by Nuc1eoN** [comment]
Added a clarification but feel free to alter it

**Comment by lancepioch** [comment]
I'm wondering if it's worth it or not to just have a separate section for each Apache and Nginx.

**Pull request merged**
