### PR TITLE
Fix EACCES error when running npm install

### PR DESCRIPTION
**Pull request by Kurounin**

### CODE REVIEW

**Comment by parkervcp** [comment]
You could at least write why this is a change that should be accepted...

**Comment by lancepioch** [comment]
@parkervcp This is in reference to this issue: https://github.com/nodejs/node-gyp/issues/1236#issuecomment-327668264

**Comment by parkervcp** [comment]
I know why it should be added. I am encouraging people to actually fill out a description for their PR's.

Something like - "resolves this issue - A link to the other issue"

**Comment by Kurounin** [comment]
@parkervcp Sorry. Will put more effort into writing a description next time.

**Pull request merged**
