### PR TITLE
Update updating.md

### PR DESCRIPTION
**Pull request by mtjohnson47**
Panel version 1.2.2 gives errors when trying to updating using php 8

### CODE REVIEW

**Comment by DaneEveritt** [comment]
I don't follow what you're fixing here, can you explain more please?

**Comment by mtjohnson47** [comment]
On 1.2.2, putting the panel in maintenance mode gives errors if using PHP 8, and has to be done with PHP7.4.  So, only update to PHP8 is already on 1.3 or higher.

**Comment by DaneEveritt** [comment]
We don't expect people to only update to a release that is no longer supported, this change is unnecessary.

**Comment by mtjohnson47** [comment]
You misunderstand.  I'm not talking about updating to 1.2.2, I'm talking about updating FROM 1.2.2.

**Comment by DaneEveritt** [comment]
Ah, I'm really not that worried about it seeing as that update has been out for months now. Not being able to put the panel into Maintenance mode isn't the end of the world, if anything someone can just move the down command above the dependency update which is probably more correct anyways.

The wording you added isn't quite intuitive (even to me) and just encourages people to not update all the way to 8, which is highly recommended to avoid having to repeat this process down the road.

**Pull request closed without merging**
