### PR TITLE
Update php to version 8.2 debian.md

### PR DESCRIPTION
**Pull request by CodeExplorerX**
Update php to version 8.2

### CODE REVIEW

**Review by CodeExplorerX — COMMENTED** [review]
Update php to version 8.2

**Comment by QuintenQVD0** [comment]
The panel does not run on PHP 8.2? aleast the queue worker does not

**Comment by CodeExplorerX** [comment]
> The panel does not run on PHP 8.2? aleast the queue worker does not

I tested it locally on Debian 12 and Ubuntu 23.04. Pteodactyl panel runs on php 8.2 as well as a queue worker

**Comment by QuintenQVD0** [comment]
> > The panel does not run on PHP 8.2? aleast the queue worker does not
> 
> I tested it locally on Debian 12 and Ubuntu 23.04. Pteodactyl panel runs on php 8.2 as well as a queue worker

Ubuntu 23.04 is not even an LTS so that to begin with is not supported. 

The queue worker does not work last time we checked. It does not run its crons that the users in the panel setup

**Comment by QuintenQVD0** [comment]
and there are way more places in the docs where php 8.1 is mentioned as we lock everything to a specific version

**Comment by CodeExplorerX** [comment]
> and there are way more places in the docs where php 8.1 is mentioned as we lock everything to a specific version

Okay, I'll try to finalize and attach all the tests

**Comment by Boy132** [comment]
> The panel does not run on PHP 8.2? aleast the queue worker does not

Since the Laravel 10 update it runs fine on php 8.2. The test even use 8.1 & 8.2.

**Comment by QuintenQVD0** [comment]
Please also see #558 and make this pr work with that.

**Comment by CodeExplorerX** [comment]
#558

**Comment by CodeExplorerX** [comment]
#558

**Comment by CodeExplorerX** [comment]
#558

**Pull request closed without merging**
