### PR TITLE
Better terminology

### PR DESCRIPTION
**Pull request by JackW6809**
Cleared up some of the wording. Not sure if all the changes I made are correct however that is the way I got it to work on my install.

### CODE REVIEW

**Comment by matthewpi** [comment]
You cannot set the mount target inside of `/home/container` anywhere.  So `/home/container`, `/home/container/folder`, etc are all not allowed.

**Comment by JackW6809** [comment]
> You cannot set the mount target inside of `/home/container` anywhere. So `/home/container`, `/home/container/folder`, etc are all not allowed.

@matthewpi Ah okay, so now what am I mean to put for the target then? An example would be great as from reading the documentation it is unclear to me thank you.

**Comment by Software-Noob** [comment]
> > You cannot set the mount target inside of `/home/container` anywhere. So `/home/container`, `/home/container/folder`, etc are all not allowed.
> 
> @matthewpi Ah okay, so now what am I mean to put for the target then? An example would be great as from reading the documentation it is unclear to me thank you.

There was supposed to be an example screenshot in the documentation, but it wasn't added to it before the PR was merged.

Here's a gmod example:

Source: /home/cstrike
Target: /cstrike
Read-only: True
User mountable: False

You also have to add it to your allowed_mount in the wings config.yml file.

**Comment by JackW6809** [comment]
> > > You cannot set the mount target inside of `/home/container` anywhere. So `/home/container`, `/home/container/folder`, etc are all not allowed.
> > 
> > 
> > @matthewpi Ah okay, so now what am I mean to put for the target then? An example would be great as from reading the documentation it is unclear to me thank you.
> 
> There was supposed to be an example screenshot in the documentation, but it wasn't added to it before the PR was merged.
> 
> Here's a gmod example:
> 
> Source: /home/cstrike
> Target: /cstrike
> Read-only: True
> User mountable: False
> 
> You also have to add it to your allowed_mount in the wings config.yml file.

Ah right, that is great thank you!

**Pull request closed without merging**
