### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by endigma-4426**

### CODE REVIEW

**Comment by endigma-4426** [comment]
ok this really seemed like a typo but its the same in the wings repo desc so ok

**Comment by Rhydium** [comment]
It is a typo..

**Comment by endigma-4426** [comment]
Ok I guess this *is* a typo, so it should be fixed here and in the repository description.

**Comment by matthewpi** [comment]
No, this is intentional.  Wings is the "server control plane" not the "server control panel".

**Comment by endigma-4426** [comment]
image
someone emailed me saying the opposite lol, this is the weirdest PR i've ever made

**Comment by victiondev** [comment]
Take it from one of the pterodactyl devs rather than a random person lol

**Comment by Rhydium** [comment]
> image
> someone emailed me saying the opposite lol, this is the weirdest PR i've ever made

I replied with that as it seemed like a typo, then I double checked and realised its intentional so I removed my comment :)

**Comment by DaneEveritt** [comment]
I'd recommend everyone use Google to look up word definitions before PRing something as a typo fix in the future.

**Pull request closed without merging**
